version: 2

updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - ".github/actions/setup-test-dependencies"
      - ".github/actions/setup-website-dependencies"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
        exclude-patterns:
          - "JackPlowman/reusable-workflows"
        update-types:
          - "patch"
          - "minor"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "website"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      javascript:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "patch"
          - "minor"
    cooldown:
      default-days: 7

  - package-ecosystem: "uv"
    directory: "tests"
    schedule:
      interval: "cron"
      cronjob: "30 7 * * *"
      timezone: "Europe/London"
    target-branch: "main"
    groups:
      python:
        applies-to: "version-updates"
        patterns:
          - "*"
    cooldown:
      default-days: 7
