name: "Setup Website Dependencies"
description: "Installs website dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js with Cache
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version-file: "website/package.json"
        cache: "npm"
        cache-dependency-path: "website/package-lock.json"
    - name: Set up Just
      uses: extractions/setup-just@53165ef7e734c5c07cb06b3c8e7b647c5aa16db3 # v4.0.0
    - name: Install website Dependencies
      shell: bash
      run: just website::install-ci
