name: "Setup website Dependencies"
description: "Installs dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js with Cache
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version-file: "website/package.json"
        cache: "npm"
        cache-dependency-path: "website/package-lock.json"
    - name: Set up Just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
    - name: Install website Dependencies
      shell: bash
      run: just website::install
