name: "Setup Website Dependencies"
description: "Installs website dependencies for the project"

runs:
  using: "composite"
  steps:
    - name: Set up Node.js with Cache
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version-file: "website/package.json"
        cache: "npm"
        cache-dependency-path: "website/package-lock.json"
    - name: Set up Just
      uses: extractions/setup-just@e33e0265a09d6d736e2ee1e0eb685ef1de4669ff # v3.0.0
    - name: Install website Dependencies
      shell: bash
      run: just website::install-ci
