name: Clean Caches

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  clean-caches:
    name: Clean Caches
    permissions:
      contents: read
    uses: JackPlowman/reusable-workflows/.github/workflows/common-clean-caches.yml@770e0f8d83d2cf12795ae93c33ff48b731c41201 # v2026.06.30.01
    secrets:
      workflow_github_token: ${{ secrets.GH_TOKEN }}
