name: "Pull Request Tasks"

on:
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  pull-requests: read

jobs:
  common-pull-request-tasks:
    name: Common Pull Request Tasks
    permissions:
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-pull-request-tasks.yml@cc8b3c353be3aa159dbd5c71fb78ba84f50873ec # v2025.07.01.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
